name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.13.1"
      - name: Docker Compose Up
        run: docker-compose up -d
      - name: Test it
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/sqlfun-dev
        run: |
          yarn install
          yarn pcq schema.sql
          yarn citest
